//
//  Activity.swift
//
//  Created by Zachary Waldowski on 8/21/16.
//  Copyright © 2016-2017 Big Nerd Ranch. Licensed under MIT.
//

import os.activity

public struct Activity {

    /// Support flags for Activity.
    public struct Options: OptionSet {
        public let rawValue: UInt32
        public init(rawValue: UInt32) {
            self.rawValue = rawValue
        }

        /// Detach a newly created activity from a parent activity, if any.
        ///
        /// If passed in conjunction with a parent activity, the activity will
        /// only note what activity "created" the new one, but will make the
        /// new activity a top level activity. This allows seeing what
        /// activity triggered work without actually relating the activities.
        public static let detached = Options(rawValue: OS_ACTIVITY_FLAG_DETACHED.rawValue)

        /// Will only create a new activity if none present.
        ///
        /// If an activity ID is already present, a new activity will be
        /// returned with the same underlying activity ID.
        public static let ifNonePresent = Options(rawValue: OS_ACTIVITY_FLAG_IF_NONE_PRESENT.rawValue)
    }

    private let reference: os_activity_t

    /// Executes a function body within the context of the activity.
    public func withActive<Return>(execute body: () throws -> Return) rethrows -> Return {
        func impl(execute work: () throws -> Return, recover: (Error) throws -> Return) rethrows -> Return {
            var result: Return!
            var error: Error?

            os_activity_apply(reference) {
                do {
                    result = try work()
                } catch let e {
                    error = e
                }
            }

            if let e = error {
                return try recover(e)
            } else {
                return result!
            }

        }

        return try impl(execute: body, recover: { throw $0 })
    }

    /// Opaque structure created by `Activity.enter()` and restored using
    /// `leave()`.
    public struct Scope {
        fileprivate var state = os_activity_scope_state_s()
        fileprivate init() {}

        /// Pops activity state to `self`.
        public mutating func leave() {
            os_activity_scope_leave(&state)
        }
    }

    /// Changes the current execution context to the activity.
    ///
    /// An activity can be created and applied to the current scope by doing:
    ///
    ///    var scope = Activity("my new activity").enter()
    ///    defer { scope.leave() }
    ///    ... do some work ...
    ///
    public func enter() -> Scope {
        var scope = Scope()
        os_activity_scope_enter(reference, &scope.state)
        return scope
    }

    /// Creates an activity.
    public init(_ description: StaticString, parent: Activity = .current, options: Options = [], dso: UnsafeRawPointer = #dsohandle) {
        self.reference = description.withUTF8Buffer { (buffer: UnsafeBufferPointer<UInt8>) -> os_activity_t in
            let dso = UnsafeMutableRawPointer(mutating: dso)
            let string = UnsafeRawPointer(buffer.baseAddress)!.assumingMemoryBound(to: Int8.self)
            let flags = os_activity_flag_t(rawValue: options.rawValue)

            return _os_activity_create(dso, string, parent.reference, flags)
        }
    }

    private init(_ opaque: OS_os_activity) {
        self.reference = opaque
    }

    /// An activity with no traits; as a parent, it is equivalent to a
    /// detached activity.
    public static var none: Activity {
        return Activity(_swift_os_activity_none())
    }

    /// The running activity.
    ///
    /// As a parent, the new activity is linked to the current activity, if one
    /// is present. If no activity is present, it behaves the same as `.none`.
    public static var current: Activity {
        return Activity(_swift_os_activity_current())
    }

    /// Label an activity auto-generated by UI with a name that is useful for
    /// debugging macro-level user actions.
    ///
    /// This function should be called early within the scope of an `IBAction`,
    /// before any sub-activities are created. The name provided will be shown
    /// in tools in addition to the system-provided name. This API should only
    /// be called once, and only on an activity created by the system. These
    /// actions help determine workflow of the user in order to reproduce
    /// problems that occur.
    ///
    /// For example, a control press and/or menu item selection can be labeled:
    ///
    ///    Activity.labelUserAction("New mail message")
    ///    Activity.labelUserAction("Empty trash")
    ///
    /// Where the underlying name will be "gesture:" or "menuSelect:".
    public static func labelUserAction(_ description: StaticString, dso: UnsafeRawPointer = #dsohandle) {
        description.withUTF8Buffer { (buffer: UnsafeBufferPointer<UInt8>) in
            let string = UnsafeRawPointer(buffer.baseAddress)!.assumingMemoryBound(to: Int8.self)
            _os_activity_label_useraction(UnsafeMutableRawPointer(mutating: dso), string)
        }
    }
    
}
